services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_mq_saga
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitMq

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379" # Porta de conexão
      - "8001:8001" # Porta do painel de controle redis insights

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432" # Porta de conexão